[package]
name = "agent-rs"
version = "0.1.0"
authors = ["Jose Antonio Delgado Alfonso <jdelgadoalfonso@openmailbox.org>"]

[dependencies]
abstract-ns = "0.4.3"
actix = "0.5.5"
actix-web = { version = "0.5.1", features=["alpn"] }
amq-protocol = "0.19.1"
bitflags = "1.0.1"
chrono = "0.4.2"
config = "0.8.0"
elastic = "0.20.9"
elastic_derive = "0.20.9"
elastic_types = "0.20.9"
elastic_types_derive = "0.20.9"
env_logger = "0.5.7"
futures = "0.1.21"
lapin-futures = "0.11.1"
log = "0.4.1"
nom = { version = "3.2.1", features = [ "nightly" ] }
ns-dns-tokio = "0.4.0"
rustls = "0.11.0"
serde = "1.0.37"
serde_derive = "1.0.37"
serde_json = "1.0.13"
tls-api = "0.1.19"
tls-api-rustls = "0.1.19"
tokio-core = "0.1.17"
tokio-io = "0.1.6"
tokio-tls-api = "0.1.19"

[profile.release]
lto = true
