[package]
name = "agent-rs"
version = "0.1.0"
authors = ["Jose Antonio Delgado Alfonso <jdelgadoalfonso@openmailbox.org>"]

[dependencies]
abstract-ns = "0.4.2"
amq-protocol = "0.19.1"
bitflags = "1.0.1"
chrono = "0.4.0"
config = "0.7.0"
env_logger = "0.4.3"
futures = "0.1.17"
lapin-futures = "0.10.0"
log = "0.3.8"
nom = { version = "3.2.1", features = [ "nightly" ] }
ns-dns-tokio = "0.4.0"
rustls = "0.11.0"
tokio-core = "0.1.11"
tls-api = "0.1.12"
tls-api-rustls = "0.1.12"
tokio-tls-api = "0.1.12"
tokio-io = "0.1.4"
