[package]
name = "agent-rs"
version = "0.1.0"
authors = ["Jose Antonio Delgado Alfonso <jdelgadoalfonso@openmailbox.org>"]

[dependencies]
actix = "0.6.1"
actix-web = { version = "0.6.15", features=["alpn"] }
amq-protocol = "0.22.0"
bitflags = "1.0.3"
chrono = "0.4.5"
config = "0.9.0"
crossbeam-channel = "0.2.4"
crossbeam-utils = "0.5.0"
dirs = "1.0.2"
elastic = "0.20.10"
elastic_derive = "0.20.10"
elastic_types = "0.20.10"
elastic_types_derive = "0.20.10"
env_logger = "0.5.12"
futures = "0.1.23"
lapin-futures = "0.13.0"
log = "0.4.3"
nom = "4.0.0"
rustls = "0.11.0"
serde = "1.0.71"
serde_derive = "1.0.71"
serde_json = "1.0.24"
tls-api = "0.1.20"
tls-api-rustls = "0.1.20"
tokio-io = "0.1.7"
tokio-tcp = "0.1.1"
tokio-tls-api = "0.1.20"
trust-dns-resolver = "0.9.1"

[profile.dev]
opt-level        = 0
debug            = true
rpath            = false
lto              = false
debug-assertions = true
codegen-units    = 1

[profile.release]
opt-level        = 3
debug            = false
rpath            = false
lto              = true
debug-assertions = false
codegen-units    = 1
